### ISSUE TITLE
这两个问题如何解决呢？

### ISSUE THREAD

**Issue by Ayingaying** [joey66666/Leava#11]
![image](https://user-images.githubusercontent.com/48882101/72681197-27ac6300-3afc-11ea-9714-22b835be0b8e.png)

**Comment by joey66666** [comment]
- 第一个要先开通微信云服务
- 第二个是数据库没有建
![image](https://user-images.githubusercontent.com/25404074/79574680-17078b00-80f3-11ea-87bc-7e5d6355fbb5.png)
查询不到数据库，无法返回给前端
