### ISSUE TITLE
Images&UI 为设计图和icon，logo 是用什么原件设计的

### ISSUE THREAD

**Issue by jili3221058001** [joey66666/Leava#5]
请问，Images&UI 为设计图和icon，logo 是用什么原件设计的？

**Comment by songyuezhong** [comment]
'mysql+mysqlconnector://user:passwd@IP:port/DB')这个不会改，能不能给个样例？

**Comment by joey66666** [comment]
> 'mysql+mysqlconnector://user:passwd@IP:port/DB')这个不会改，能不能给个样例？

要新建mysql数据库
[超详细MySQL安装及基本使用教程](https://blog.csdn.net/bobo553443/article/details/81383194)
sample：本地mysql数据库，root用户密码为123456，端口默认3306，数据库名为leava
‘mysql+mysqlconnector://root:123456@127.0.0.1:3306/leava’

**Comment by joey66666** [comment]
> 请问下载下来自己不会搭建运行环境呢，求大神指导下，好无助

小程序不需要搭建后端运行环境，直接小程序开发工具导入
[微信小程序导入已有项目](https://blog.csdn.net/janny_flower/article/details/80681049)
