### ISSUE TITLE
能不能写个搭建教程？

### ISSUE THREAD

**Issue by songyuezhong** [joey66666/Leava#6]
我是小白，看了楼主的介绍 还是不会搭建，请教应该如何 搭建啊， 我是小白，特别想试下大神的程序 啊，求指导，出个搭建教程，在此感谢了，谢谢
另外这个数据库我也不会修改，'mysql+mysqlconnector://user:passwd@IP:port/DB')这个不会改，能不能给个样例？

**Comment by joey66666** [comment]
> 我是小白，看了楼主的介绍 还是不会搭建，请教应该如何 搭建啊， 我是小白，特别想试下大神的程序 啊，求指导，出个搭建教程，在此感谢了，谢谢
> 另外这个数据库我也不会修改，'mysql+mysqlconnector://user:passwd@IP:port/DB')这个不会改，能不能给个样例？

好的，我有空会写的，谢谢关注

**Comment by joey66666** [comment]
> 我是小白，看了楼主的介绍 还是不会搭建，请教应该如何 搭建啊， 我是小白，特别想试下大神的程序 啊，求指导，出个搭建教程，在此感谢了，谢谢
> 另外这个数据库我也不会修改，'mysql+mysqlconnector://user:passwd@IP:port/DB')这个不会改，能不能给个样例？

https://github.com/joey66666/Leava/issues/10
