### ISSUE TITLE
大佬，新问题

### ISSUE THREAD

**Issue by songyuezhong** [joey66666/Leava#7]
大佬，前端安装了小程序工具，可以运行，但是无法登录，我在本地新建了数据库，但是后台文件是怎么运行的啊？是不是要安装python运行后台程序 ？

**Comment by songyuezhong** [comment]
D:\Leava-master\Leava-master\backend>python RESTful_backend.py
Traceback (most recent call last):
  File "RESTful_backend.py", line 14, in <module>
    from flask import Flask, jsonify, abort, request
ModuleNotFoundError: No module named 'flask' 大哥，安装 完python运行不了后台文件啊，是不是还缺少东西？

**Comment by songyuezhong** [comment]
D:\>cd Leava-master\Leava-master\backend

D:\Leava-master\Leava-master\backend>python RESTful_backend.
 * Serving Flask app "test" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a
nt.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 171-749-072
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
大哥，后台运行起来是这样的嘛？怎么http地址不怎么对啊？

**Comment by songyuezhong** [comment]
折腾了一下午，还是不能运行啊，好像连接不进去，是不是数据库哪里设置有问题？只有开始界面，进不了里面去，求大神指导下啊，想哭

**Comment by joey66666** [comment]
> 折腾了一下午，还是不能运行啊，好像连接不进去，是不是数据库哪里设置有问题？只有开始界面，进不了里面去，求大神指导下啊，想哭

后端启动正确的，提示是说当前仅适用于调试环境
