### ISSUE TITLE
老大，运行前端之后变成这样的了呢？求指导

### ISSUE THREAD

**Issue by songyuezhong** [joey66666/Leava#8]
Request URL:http://127.0.0.1/login
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
content-type:application/json
Origin:http://127.0.0.1:54496
Referer:http://127.0.0.1:54496/appservice/appservice?t=1562236750469?load
User-Agent:wechatdevtools appservice port/10069 token/c7aa8308f67ad7e123beccd32ae56d85 
Request Payload
view source
{userId: "1", userPwd: "123"}
userId
:
"1"
userPwd
:
"123"

到底应该怎么处理啊？就是连接不进数据库里，哪里出现了问题？求指导下啊，哥

**Comment by songyuezhong** [comment]
Thu Jul 04 2019 19:03:40 GMT+0800 (中国标准时间) 配置中关闭合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书检查
VM54:1 工具未校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书。
console.warn @ VM54:1
n @ appservice?t=1562238210463:1574
h @ appservice?t=1562238210463:1574
createRequestTask @ appservice?t=1562238210463:1574
invoke @ appservice?t=1562238210463:1574
invoke @ WAService.js:4
V @ WAService.js:6
K @ WAService.js:6
Wt @ WAService.js:7
e @ WAService.js:13
(anonymous) @ WAService.js:13
(anonymous) @ WAService.js:6
(anonymous) @ WAService.js:7
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
submit @ index.js? [sm]:144
(anonymous) @ WAService.js:20
l @ WAService.js:19
Rt @ WAService.js:20
dn @ WAService.js:20
(anonymous) @ WAService.js:20
(anonymous) @ WAService.js:19
(anonymous) @ WAService.js:11
n @ WAService.js:6
e @ appservice?t=1562238210463:1574
r.registerCallback.t @ appservice?t=1562238210463:1574
l.forEach.t @ appservice?t=1562238210463:1574
(anonymous) @ appservice?t=1562238210463:1574
s.onmessage @ appservice?t=1562238210463:1574
appservice?t=1562238210463:1574 POST http://127.0.0.1/login net::ERR_CONNECTION_REFUSED
h @ appservice?t=1562238210463:1574
createRequestTask @ appservice?t=1562238210463:1574
invoke @ appservice?t=1562238210463:1574
invoke @ WAService.js:4
V @ WAService.js:6
K @ WAService.js:6
Wt @ WAService.js:7
e @ WAService.js:13
(anonymous) @ WAService.js:13
(anonymous) @ WAService.js:6
(anonymous) @ WAService.js:7
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
submit @ index.js? [sm]:144
(anonymous) @ WAService.js:20
l @ WAService.js:19
Rt @ WAService.js:20
dn @ WAService.js:20
(anonymous) @ WAService.js:20
(anonymous) @ WAService.js:19
(anonymous) @ WAService.js:11
n @ WAService.js:6
e @ appservice?t=1562238210463:1574
r.registerCallback.t @ appservice?t=1562238210463:1574
l.forEach.t @ appservice?t=1562238210463:1574
(anonymous) @ appservice?t=1562238210463:1574
s.onmessage @ appservice?t=1562238210463:1574
WAService.js:19 Invoke event submit in page: page/index/index
appservice?t=1562238210463:1574 POST http://127.0.0.1/login net::ERR_CONNECTION_REFUSED

**Comment by songyuezhong** [comment]
http://127.0.0.1/login 前台代码里的地址在微信工具里根本无法访问到啊？这地方是不是要修改？怎么改啊？愁死了

**Comment by songyuezhong** [comment]
现在又一直显示 学号和工号不存在，但是我自己在数据库里添加了一条账号啊，还是登录 不了，郁闷

**Comment by wanshunwen** [comment]
你好，加个联系方式呗 我也没弄明白 咱俩研究研究 qq:1078998001

**Comment by joey66666** [comment]
> http://127.0.0.1/login 前台代码里的地址在微信工具里根本无法访问到啊？这地方是不是要修改？怎么改啊？愁死了

不用改，这就是登陆的后端api，位置在后端py文件45行

**Comment by joey66666** [comment]
> Thu Jul 04 2019 19:03:40 GMT+0800 (中国标准时间) 配置中关闭合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书检查
> VM54:1 工具未校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书。
> console.warn @ VM54:1
> n @ appservice?t=1562238210463:1574
> h @ appservice?t=1562238210463:1574
> createRequestTask @ appservice?t=1562238210463:1574
> invoke @ appservice?t=1562238210463:1574
> invoke @ WAService.js:4
> V @ WAService.js:6
> K @ WAService.js:6
> Wt @ WAService.js:7
> e @ WAService.js:13
> (anonymous) @ WAService.js:13
> (anonymous) @ WAService.js:6
> (anonymous) @ WAService.js:7
> (anonymous) @ WAService.js:15
> (anonymous) @ WAService.js:6
> submit @ index.js? [sm]:144
> (anonymous) @ WAService.js:20
> l @ WAService.js:19
> Rt @ WAService.js:20
> dn @ WAService.js:20
> (anonymous) @ WAService.js:20
> (anonymous) @ WAService.js:19
> (anonymous) @ WAService.js:11
> n @ WAService.js:6
> e @ appservice?t=1562238210463:1574
> r.registerCallback.t @ appservice?t=1562238210463:1574
> l.forEach.t @ appservice?t=1562238210463:1574
> (anonymous) @ appservice?t=1562238210463:1574
> s.onmessage @ appservice?t=1562238210463:1574
> appservice?t=1562238210463:1574 POST http://127.0.0.1/login net::ERR_CONNECTION_REFUSED
> h @ appservice?t=1562238210463:1574
> createRequestTask @ appservice?t=1562238210463:1574
> invoke @ appservice?t=1562238210463:1574
> invoke @ WAService.js:4
> V @ WAService.js:6
> K @ WAService.js:6
> Wt @ WAService.js:7
> e @ WAService.js:13
> (anonymous) @ WAService.js:13
> (anonymous) @ WAService.js:6
> (anonymous) @ WAService.js:7
> (anonymous) @ WAService.js:15
> (anonymous) @ WAService.js:6
> submit @ index.js? [sm]:144
> (anonymous) @ WAService.js:20
> l @ WAService.js:19
> Rt @ WAService.js:20
> dn @ WAService.js:20
> (anonymous) @ WAService.js:20
> (anonymous) @ WAService.js:19
> (anonymous) @ WAService.js:11
> n @ WAService.js:6
> e @ appservice?t=1562238210463:1574
> r.registerCallback.t @ appservice?t=1562238210463:1574
> l.forEach.t @ appservice?t=1562238210463:1574
> (anonymous) @ appservice?t=1562238210463:1574
> s.onmessage @ appservice?t=1562238210463:1574
> WAService.js:19 Invoke event submit in page: page/index/index
> appservice?t=1562238210463:1574 POST http://127.0.0.1/login net::ERR_CONNECTION_REFUSED

微信小程序默认https交互以保证安全，这里要http可以用于本地开发调试不能用于正式部署

**Comment by joey66666** [comment]
> 现在又一直显示 学号和工号不存在，但是我自己在数据库里添加了一条账号啊，还是登录 不了，郁闷

修改后端py文件连接数据库的地方，改成本地数据库地址+端口+用户名+密码，库名&表名&字段名与本地已建立数据库对应。“学号和工号不存在”的问题可能出在数据库没连上/ 库名/ 表名/ 字段名 没对应
