### ISSUE TITLE
发了这么多也不回

### ISSUE THREAD

**Issue by songyuezhong** [joey66666/Leava#9]
大哥，就是卡在登录 这了，获取不到数据库数据 ，返回的是0，不知道问题出在哪里？数据库我也照着你给的自己创建了，天啊，我到底该怎么办啊？

**Comment by songyuezhong** [comment]
死活获取 不到数据库里的账号和密码，大哥是怎么操作的，我实在找不到问题所在，能提示下么

**Comment by joey66666** [comment]
> 死活获取 不到数据库里的账号和密码，大哥是怎么操作的，我实在找不到问题所在，能提示下么

**数据库是建立在本地的**
1. 先在电脑上安装MySQL数据库
2. 设置好数据库端口和用户名+密码
3. 按照[数据库设计](https://github.com/joey66666/Leava/blob/master/docs/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%95%B0%E6%8D%AE%E5%BA%93%E8%AE%BE%E8%AE%A1.md)建立好对应的三个表，字段名及数据类型一一对应
4. 在[后端代码](https://github.com/joey66666/Leava/blob/master/backend/RESTful_backend.py)中修改第32行

例如：用户名root，密码123456，数据库建立在本地，端口8080，数据库名为leava
> 修改前：app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://user:passwd@IP:port/DB'

> 修改后：app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://root:123456@127.0.0.1:3306/leava'

**Comment by joey66666** [comment]
> 死活获取 不到数据库里的账号和密码，大哥是怎么操作的，我实在找不到问题所在，能提示下么

**数据库是建立在本地的，密码是自己设定的/默认的**

1. 先在电脑上安装MySQL数据库
2. 设置好数据库端口和用户名+密码
3. 按照数据库设计建立好对应的三个表，字段名及数据类型一一对应
4. 在后端代码中修改第32行和第368行
例：用户名root，密码123456，数据库建立在本地，端口8080，数据库名为leava

> 修改前：app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://user:passwd@IP:port/DB'

> 修改后：app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://root:123456@127.0.0.1:3306/leava'

**Comment by joey66666** [comment]
> 死活获取 不到数据库里的账号和密码，大哥是怎么操作的，我实在找不到问题所在，能提示下么

**数据库是建立在本地的，密码是自己设定的/默认的**

1. 先在电脑上安装MySQL数据库
2. 设置好数据库端口和用户名+密码
3. 按照数据库设计建立好对应的三个表，字段名及数据类型一一对应
4. 在后端代码中修改第32行和第368行
例：用户名root，密码123456，数据库建立在本地，端口3306，数据库名为leava
> 修改前：app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://user:passwd@IP:port/DB'

> 修改后：app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://root:123456@127.0.0.1:3306/leava'
